# refer to https://app.koofr.net/links/90cbd5aa-ef70-4f5e-99bc-f12e5a89380e?path=%2F2021-04-03T19-39-50_cin_transformer%2Fconfigs%2F2021-04-03T19-39-50-project.yaml
seed_everything: true
trainer:
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  devices: 1
  num_nodes: 1
  precision: 16-mixed
  max_epochs: 80
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  gradient_clip_val: 1.0
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "/vq/llama_log/emas"
        save_top_k: 5
        monitor: "val/loss"
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: "/vq/llama_log/emas"
      version: "n16384"
      name:

model:
  class_path: taming.models.cond_transformer.Net2NetTransformer
  init_args:
    learning_rate: 1e-4
    cond_stage_key: coord
    sos_token: 0
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 16384 
        block_size: 512
        n_layer: 24
        n_head: 16
        n_embd: 1024

    first_stage_config:
      target: taming.models.vq.VQModel
      params:
        ckpt_path: "/vq/vq_log/ffhq_256/epoch=84-step=79730.ckpt" #specify your path for tokenizer 
        use_ema: True
        model_type: "full"
        stage: transformer
        ddconfig:
          double_z: False
          z_channels: 32
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1,1,2,2,4]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [16]
          dropout: 0.0
        quantconfig:
          target: taming.modules.vqvae.quantize.ASVQ
          params:
            n_e: 16384
            e_dim: 32
            beta: 0.33
            fixed_cb: false
            use_ema_scale: true
        lossconfig:
          target: taming.modules.losses.DummyLoss
    cond_stage_config:
      target: taming.modules.misc.coord.CoordStage
      params:
        n_embed: 16384
        down_factor: 16


data:
  class_path: main.DataModuleFromConfig
  init_args:
    batch_size: 64
    num_workers: 8
    train:
      target: taming.data.faceshq.FFHQTrain
      params:
        size: 256
        coord: True

    validation:
      target: taming.data.faceshq.FFHQValidation
      params:
        size: 256
        coord: True

    test:
      target: taming.data.faceshq.FFHQValidation
      params:
        size: 256
        coord: True

ckpt_path: null # to resume
