seed_everything: true
trainer:
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  devices: 2
  num_nodes: 1
  precision: 16-mixed
  max_epochs: 100
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 80
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "/vq/vq_log/imagenet_256" # Please specify your own path
        save_top_k: -1 # save all checkpoints
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
        save_dir: "/vq/vq_log/imagenet_256" #Please specify your own path
        version: "n262k_d32"
        name:

model:
  class_path: taming.models.vq.VQModel
  init_args:
    model_type: "full"  # Options: "light" (simpler, faster) or "full" (with attention and timestep support)
    ddconfig:
      double_z: False
      z_channels: 32
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    quantconfig:
      target: taming.modules.vqvae.quantize.ASVQ
      params:
        n_e: 262144 
        e_dim: 32
        beta: 0.33
        legacy: false

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 0 # from 0 epoch
        gen_loss_weight: 0.2
        vq_weight: 1.0

    learning_rate: 1e-4
    scheduler_type: "linear-warmup_cosine-decay"
    warmup_steps: 10000 
    min_learning_rate: 1e-5
    use_ema: true

data:
  class_path: main.DataModuleFromConfig
  init_args:
    batch_size: 32
    num_workers: 8

    train:
      target: taming.data.imagenet.ImageNetTrain
      params:
        size: 256
        subset:
    validation:
      target: taming.data.imagenet.ImageNetValidation
      params:
        size: 256
        subset:
    test:
      target: taming.data.imagenet.ImageNetValidation
      params:
        size: 256
        subset:
ckpt_path: null # to resume